name: UI Tests

on:
  push:
    branches:
      - Simple

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run UI tests
        run: |
          bash ./gradlew clean test \
          -Dselenide.headless=true \
          -Dchromeoptions.args="--no-sandbox,--disable-dev-shm-usage"

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: build/allure-results

      - name: Download allurectl
        if: always()
        run: |
          curl -L https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -o allurectl
          chmod +x allurectl

      - name: Upload results to Allure TestOps
        if: always()
        env:
          ALLURE_ENDPOINT: ${{ secrets.ALLURE_ENDPOINT }}
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}
        run: |
          ./allurectl upload build/allure-results